# Generated by Django 3.1.2 on 2024-01-19 16:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_update', models.DateTimeField(auto_now=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='blog/posts/', verbose_name='Post Image')),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('posttags', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags')),
                ('post_Slug', models.SlugField(allow_unicode=True, blank=True, max_length=500, null=True, unique=True, verbose_name='Slugfiy')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.profile')),
                ('post_supercategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.supercategory', verbose_name='Super Category')),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(verbose_name='Enter Comment')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ('-comment_date',),
            },
        ),
    ]
