# Generated by Django 3.1.2 on 2024-01-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CARImage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 1372px X 830px', null=True, upload_to='carousel/', verbose_name='Image')),
                ('CARtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('CARURL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadTextAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Title')),
                ('ad_URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 540px x 769px, 250 KB MAX', null=True, upload_to='ads/daily/', verbose_name='Image')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('ad_URL', models.URLField(blank=True, null=True)),
                ('image_position', models.CharField(choices=[('Right', 'Right')], default='Right', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdMiddlebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 768px x 450px, 250 KB MAX', null=True, upload_to='ads/middlebar/', verbose_name='Image')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('ad_URL', models.URLField(blank=True, null=True)),
                ('image_position', models.CharField(choices=[('Right', 'Right')], default='Right', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 760px x 596px, 250 KB MAX', null=True, upload_to='ads/sidebar/', verbose_name='Image')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('ad_URL', models.URLField(blank=True, null=True)),
                ('image_position', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 756px x 332px, 250 KB MAX', null=True, upload_to='ads/suppliers/', verbose_name='Image')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('ad_URL', models.URLField(blank=True, null=True, verbose_name='Supplier')),
                ('image_position', models.CharField(choices=[('Left', 'Left')], default='Left', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='HotDealAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 508px x 332px, 250 KB MAX', null=True, upload_to='ads/hot-deal-ad/', verbose_name='Image')),
                ('rate', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Discount Percentage')),
                ('ad_URL', models.URLField(blank=True, null=True)),
                ('image_position', models.CharField(choices=[('Right', 'Right')], default='Right', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetailsAdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 360px x 250px, 250 KB MAX', null=True, upload_to='ads/vendor-page/', verbose_name='Image')),
                ('ad_URL', models.URLField(blank=True, null=True, verbose_name='Product URL')),
            ],
        ),
        migrations.CreateModel(
            name='ShopAdSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 1024px x 1076px, 250 KB MAX', null=True, upload_to='ads/shop-ad/', verbose_name='Image')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('ad_URL', models.URLField(blank=True, null=True)),
                ('image_position', models.CharField(choices=[('Right', 'Right')], default='Right', max_length=13)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdDealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_mage', models.ImageField(blank=True, help_text='Please use our recommended dimensions: 568px x 503px, 250 KB MAX', null=True, upload_to='ads/deal-time/', verbose_name='Image')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('supplier_URL', models.URLField(blank=True, null=True, verbose_name='supplier URL')),
                ('ad_URL', models.URLField(blank=True, null=True, verbose_name='Product URL')),
                ('PRDPrice', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('PRDDiscountPrice', models.FloatField(blank=True, null=True, verbose_name='Discount')),
                ('PRDdealtime', models.DateTimeField(blank=True, null=True, verbose_name='Deal Time')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Supplier')),
            ],
        ),
    ]
